### ISSUE TITLE
Show mjml compilation errors in browser previews

### ISSUE THREAD

**Issue by psugihara** [psugihara/mailing#27]
Sometimes there are mjml compilation errors returned from the render function as well as valid HTML. Currently we display the preview if there's any html but abort sending the email if there are any errors. So you may think you have a good email and it'll only fail when you try to send. Instead, it would be better to display the errors on the preview page so that you know to fix them.

**Comment by alexfarrill** [comment]
Example: render an `MjmlImage` block with an invalid value, e.g. `width="300"` (omitting "px").  The MJML compiler outputs an error to the console, but the preview renders fine.  Instead, the preview should show the error or direct the user to the console.

**Comment by alexfarrill** [comment]
fixed by https://github.com/psugihara/mailing/pull/36
